### ISSUE TITLE
Doesn't work for AdGuard and uBlock Origin

### ISSUE THREAD

**Issue by sergeysinyavsky** [potatojam/defold-adblock-detector#1]
Unfortunately, AdGuard and uBlock Origin extensions somehow bypass the detection.
Adguard works for the first time, but after reloading the page it doesn't work

**Comment by AGulev** [comment]
maybe we should use newer detection lib?

**Comment by sergeysinyavsky** [comment]
@AGulev this is the only normal one i found.
I tried to do it like this, but still my AdGuard passed the test. I don't know if it works for uBlock Origin.
https://github.com/google/site-kit-wp/blob/856bf8ba55e6d6d244869837082a31a01c7b383e/assets/js/modules/adsense/datastore/adblocker.js#L66-L90

		if ( await detectAnyAdblocker() ) {
			return true;
		}
		// The above is good about detecting most adblockers.
		// For the rest, we'll make a placeholder request to the favicon with some
		// additional stuff in the query string to (hopefully) trigger a filter.
		// If this throws, then the fetch request failed completely and we'll assume it was blocked.
		try {
			const params = [
				// The name of the parameter here doesn't really matter
				// since adblockers look at the URL as a whole.
				// Note: this value must not be URL-encoded.
				'google-site-kit=/adsense/pagead2.googlesyndication.com/pagead/js/adsbygoogle.js',
				// Add a timestamp for cache-busting.
				`timestamp=${ Date.now() }`,
			];
			await fetch( `/favicon.ico?${ params.join( '&' ) }`, {
				credentials: 'omit',
				// Don't follow any redirects; we only care about this request being blocked or not.
				redirect: 'manual',
			} );
		} catch {
			return true;
		}
		return false;

**Comment by sergeysinyavsky** [comment]
I'll try the method from here:
https://incolumitas.com/2020/12/27/detecting-uBlock-Origin-and-Adblock-Plus-with-JavaScript-only/

**Comment by sergeysinyavsky** [comment]
The method described on the website worked.
